### ISSUE TITLE
Titles not showing on Zotero

### ISSUE THREAD

**Issue by amandhiraj** [hack-r/pyserpZotero#3]
Hey, I'm using the latest version and there are some errors:

**Error#1:**  `SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 18-19: truncated \uXXXX escape`
**Line of cause 358:** `item['data'][FIELD] = item['data'][FIELD].replace("{\’{\u}}","u")` 

**Error#2:** Titles do not get uploaded. It is blank.

Would you be able to provide some answers or solutions to this?

**Comment by GlobalMin** [comment]
This is my fault. I have made a PR to fix the notebook and if any bugs are still present, I'll address later.

**Comment by GlobalMin** [comment]
@amandhiraj  If you use [this PR](https://github.com/hack-r/pyserpZotero/pull/4) and pull the change to your local code base, it should fix the problem until it's merged into main.

**Comment by hack-r** [comment]
Totally worth the 24-hour glitch. I'll merge it later tonight or tomorrow. Much appreciated!
